name: Social Media Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
  path: ["platforms/socialmedia/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: socialmedia
      app_path: platforms/socialmedia
      namespace: platforms
