name: Homepage Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
  path: ["platforms/homepage/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: homepage
      app_path: platforms/homepage
      namespace: platforms
