name: Tools Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
  path: ["platforms/tools/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: tools
      app_path: platforms/tools
      namespace: platforms
