name: OnCall Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
  path: ["platforms/oncall/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: oncall
      app_path: platforms/oncall
      namespace: platforms
