name: API Test Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ["platforms/apitest/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: apitest
      app_path: platforms/apitest
      namespace: platforms
