name: Password Deploy
on:
  push:
    branches: [master]
  paths: ["platforms/password/**"]

jobs:
  Deploy:
    uses: ./.github/workflows/reusable-deployment-docker.yaml
    with:
      app_name: password
      app_path: platforms/password
      namespace: platforms
